# Generated by Django 5.0.2 on 2024-03-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='value_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='value_ckb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='value_en',
            field=models.TextField(null=True),
        ),
    ]
