# Generated by Django 5.0.2 on 2024-03-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_application_value_ar_application_value_ckb_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
