# Generated by Django 5.0.2 on 2024-03-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='text_ar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_ckb',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_en',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
