# Generated by Django 5.0.2 on 2024-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_text_ar_contact_text_ckb_contact_text_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
