# Generated by Django 4.1.13 on 2024-02-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
