# Generated by Django 5.0.2 on 2024-03-17 17:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='content_ar',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='content_ckb',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='content_en',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
