# Generated by Django 4.1.13 on 2024-03-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile_arabic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ku',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
