# Generated by Django 5.0.2 on 2024-03-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorprofile_content_ar_doctorprofile_content_ckb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorresume',
            name='icon',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
