# Generated by Django 4.1.13 on 2024-03-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorprofile_description_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='description_ku',
            new_name='description_ckb',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='name_ku',
            new_name='name_ckb',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='specialty_ku',
            new_name='specialty_ckb',
        ),
    ]
