# Generated by Django 4.1.13 on 2024-03-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_description_ku_doctorprofile_description_ckb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='description_ckb',
            new_name='description_ku',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='name_ckb',
            new_name='name_ku',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='specialty_ckb',
            new_name='specialty_ku',
        ),
    ]
