# Generated by Django 5.0.2 on 2024-03-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctorresume_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorresume',
            name='icon',
        ),
    ]
