# Generated by Django 4.1.13 on 2024-02-18 14:58

from django.db import migrations, models
import src.core.modules


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_doctorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(blank=True, default='uploads/user/default-user-avatar.png', null=True, upload_to=src.core.modules.upload_image_file_path),
        ),
    ]
