# Generated by Django 5.0.2 on 2024-03-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_doctorresume_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorresume',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
