# Generated by Django 4.1.13 on 2024-02-18 14:59

from django.db import migrations, models
import src.core.modules


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctorprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='uploads/user/default-user-avatar.png', null=True, upload_to=src.core.modules.upload_image_file_path),
        ),
    ]
