# Generated by Django 5.0.2 on 2024-03-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctorresume_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorresume',
            name='featured',
        ),
        migrations.AddField(
            model_name='titlechoice',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
