# Generated by Django 5.0.2 on 2024-03-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_doctorresume_featured_titlechoice_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_tabs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.TextField(blank=True, default=''),
        ),
    ]
