# Generated by Django 4.1.13 on 2024-03-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_description_ku_doctorprofile_description_ckb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='description_ckb',
            new_name='description_af',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='name_ckb',
            new_name='description_ar_dz',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='specialty_ckb',
            new_name='specialty_af',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ig',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_kab',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_tg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_tk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_af',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ar_dz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ig',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_kab',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_tg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_tk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ar_dz',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ast',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_be',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_bg',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_bn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_br',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_bs',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ca',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_cs',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_cy',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_da',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_dsb',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_el',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_en_au',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_en_gb',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_eo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_es_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_es_co',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_es_mx',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_es_ni',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_es_ve',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_et',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_eu',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_fa',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_fi',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_fy',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ga',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_gd',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_gl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_he',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_hi',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_hr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_hsb',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_hu',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_hy',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ia',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ig',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ind',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_io',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_is',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_it',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ja',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ka',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_kab',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_kk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_km',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_kn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ko',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ky',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_lb',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_lt',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_lv',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_mk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ml',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_mn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_mr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ms',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_my',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_nb',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ne',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_nl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_nn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_os',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_pa',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_pl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_pt',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_pt_br',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ro',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_sk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_sl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_sq',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_sr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_sr_latn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_sv',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_sw',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ta',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_te',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_tg',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_th',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_tk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_tr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_tt',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_udm',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_uk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ur',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_uz',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_vi',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_zh_hans',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_zh_hant',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
