# Generated by Django 5.0.2 on 2024-03-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_description_af_doctorprofile_description_ckb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='arabic_name',
        ),
    ]
