# Generated by Django 5.0.2 on 2024-03-04 12:50

import src.core.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_doctorprofile_arabic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, default='uploads/user/default-user-avatar.jpg', null=True, upload_to=src.core.modules.upload_image_file_path)),
            ],
        ),
    ]
