# Generated by Django 5.0.2 on 2024-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_ckb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
