# Generated by Django 5.0.2 on 2024-03-05 07:50

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_patient_user_user_is_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='country',
            field=django_countries.fields.CountryField(default='iq', max_length=2),
            preserve_default=False,
        ),
    ]
