# Generated by Django 5.0.2 on 2024-03-05 07:51

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_patient_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('asciiname', models.CharField(max_length=200)),
                ('alternatenames', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('population', models.BigIntegerField()),
                ('timezone', models.CharField(max_length=40)),
                ('modification_date', models.DateField()),
            ],
        ),
    ]
