# Generated by Django 5.0.2 on 2024-03-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_patient_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='country',
        ),
    ]
