# Generated by Django 5.0.2 on 2024-03-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_patient_country_ar_patient_country_ckb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='Slemani', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='city_ar',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='city_ckb',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='city_en',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
