# Generated by Django 5.0.2 on 2024-03-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_patient_city_patient_city_ar_patient_city_ckb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='city_ar',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='city_ckb',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='country_ar',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='country_ckb',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='country_en',
        ),
    ]
