# Generated by Django 5.0.2 on 2024-03-05 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_patient_city_ar_remove_patient_city_ckb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ar', models.CharField(max_length=50, null=True)),
                ('name_ckb', models.CharField(max_length=50, null=True)),
                ('ordinal', models.SmallIntegerField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='accounts.doctorprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
