# Generated by Django 5.0.2 on 2024-03-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_doctorlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlocation',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='doctorlocation',
            name='name_ckb',
        ),
        migrations.RemoveField(
            model_name='doctorlocation',
            name='name_en',
        ),
    ]
