# Generated by Django 5.0.2 on 2024-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_doctorlocation_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlocation',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorlocation',
            name='name_ckb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorlocation',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
