# Generated by Django 5.0.2 on 2024-03-06 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_doctorlocation_name_ar_doctorlocation_name_ckb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('education', 'Education'), ('experience', 'Experience'), ('achievement', 'Achievement'), ('special_expertise', 'Special Expertise'), ('member_of_foundation', 'Member of Foundation')], default='education', max_length=50)),
                ('title_en', models.CharField(choices=[('education', 'Education'), ('experience', 'Experience'), ('achievement', 'Achievement'), ('special_expertise', 'Special Expertise'), ('member_of_foundation', 'Member of Foundation')], default='education', max_length=50, null=True)),
                ('title_ar', models.CharField(choices=[('education', 'Education'), ('experience', 'Experience'), ('achievement', 'Achievement'), ('special_expertise', 'Special Expertise'), ('member_of_foundation', 'Member of Foundation')], default='education', max_length=50, null=True)),
                ('title_ckb', models.CharField(choices=[('education', 'Education'), ('experience', 'Experience'), ('achievement', 'Achievement'), ('special_expertise', 'Special Expertise'), ('member_of_foundation', 'Member of Foundation')], default='education', max_length=50, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_ckb', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume', to='accounts.doctorprofile')),
            ],
        ),
    ]
