# Generated by Django 5.0.2 on 2024-03-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_doctorresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=50)),
                ('display_en', models.CharField(max_length=50, null=True)),
                ('display_ar', models.CharField(max_length=50, null=True)),
                ('display_ckb', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorresume',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='doctorresume',
            name='title_ckb',
        ),
        migrations.RemoveField(
            model_name='doctorresume',
            name='title_en',
        ),
        migrations.AlterField(
            model_name='doctorresume',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='accounts.titlechoice'),
        ),
    ]
