# Generated by Django 5.0.2 on 2024-03-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_titlechoice_remove_doctorresume_title_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorresume',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='accounts.doctorprofile'),
        ),
    ]
