# Generated by Django 5.0.2 on 2024-03-06 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_doctorresume_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorresume',
            options={'ordering': ['id', 'title', 'created']},
        ),
        migrations.AlterField(
            model_name='doctorresume',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='accounts.titlechoice'),
        ),
    ]
