# Generated by Django 5.0.2 on 2024-03-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_doctorresume_options_alter_doctorresume_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='journey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
