# Generated by Django 5.0.2 on 2024-03-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_doctorprofile_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='journey_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='journey_ckb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='journey_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
