# Generated by Django 5.0.2 on 2024-03-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_doctorprofile_journey_ar_doctorprofile_journey_ckb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='field',
            field=models.CharField(default='MD', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty_ar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty_ckb',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty_en',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
