# Generated by Django 5.0.2 on 2024-03-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_doctorprofile_field_alter_doctorprofile_specialty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialty_ar',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialty_ckb',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialty_en',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='field_ar',
            field=models.CharField(default='MD', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='field_ckb',
            field=models.CharField(default='MD', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='field_en',
            field=models.CharField(default='MD', max_length=30, null=True),
        ),
    ]
