# Generated by Django 5.0.2 on 2024-03-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_doctorprofile_specialty_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlechoice',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
