# Generated by Django 5.0.2 on 2024-03-16 17:18

import django.db.models.deletion
import src.core.modules
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('title_ckb', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=650)),
                ('description_en', models.CharField(max_length=650, null=True)),
                ('description_ar', models.CharField(max_length=650, null=True)),
                ('description_ckb', models.CharField(max_length=650, null=True)),
                ('action', models.CharField(max_length=50)),
                ('action_en', models.CharField(max_length=50, null=True)),
                ('action_ar', models.CharField(max_length=50, null=True)),
                ('action_ckb', models.CharField(max_length=50, null=True)),
                ('link', models.CharField(blank=True, default='/', max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='uploads/user/default-user-avatar.png', null=True, upload_to=src.core.modules.upload_image_file_path)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('title_ckb', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('text_en', models.CharField(max_length=50, null=True)),
                ('text_ar', models.CharField(max_length=50, null=True)),
                ('text_ckb', models.CharField(max_length=50, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_details', to='core.journey')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.SmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('name_ckb', models.CharField(max_length=255, null=True)),
                ('link', models.CharField(blank=True, null=True)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='core.menu')),
            ],
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ckb', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
                ('description_ckb', models.TextField(null=True, verbose_name='Description')),
                ('title_translated', models.JSONField(blank=True, null=True, verbose_name='Translated Title')),
                ('description_translated', models.JSONField(blank=True, null=True, verbose_name='Translated Description')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='core.sectioncontent')),
            ],
            options={
                'verbose_name': 'Section Content',
                'verbose_name_plural': 'Section Contents',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('title_ckb', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=750, null=True)),
                ('description_en', models.CharField(blank=True, max_length=750, null=True)),
                ('description_ar', models.CharField(blank=True, max_length=750, null=True)),
                ('description_ckb', models.CharField(blank=True, max_length=750, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('detailed_description_en', models.TextField(blank=True, null=True)),
                ('detailed_description_ar', models.TextField(blank=True, null=True)),
                ('detailed_description_ckb', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='uploads/user/default-user-avatar.png', null=True, upload_to=src.core.modules.upload_image_file_path)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('title_ckb', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=300)),
                ('description_en', models.CharField(max_length=300, null=True)),
                ('description_ar', models.CharField(max_length=300, null=True)),
                ('description_ckb', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(blank=True, default='uploads/user/default-user-avatar.png', null=True, upload_to=src.core.modules.upload_image_file_path)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('text_en', models.CharField(max_length=200, null=True)),
                ('text_ar', models.CharField(max_length=200, null=True)),
                ('text_ckb', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('title_ckb', models.CharField(max_length=100, null=True)),
                ('conditions_description', models.TextField(blank=True, null=True)),
                ('conditions_description_en', models.TextField(blank=True, null=True)),
                ('conditions_description_ar', models.TextField(blank=True, null=True)),
                ('conditions_description_ckb', models.TextField(blank=True, null=True)),
                ('procedure_description', models.TextField(blank=True, null=True)),
                ('procedure_description_en', models.TextField(blank=True, null=True)),
                ('procedure_description_ar', models.TextField(blank=True, null=True)),
                ('procedure_description_ckb', models.TextField(blank=True, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_en', models.CharField(max_length=50, null=True)),
                ('title_ar', models.CharField(max_length=50, null=True)),
                ('title_ckb', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('description_en', models.CharField(blank=True, max_length=300, null=True)),
                ('description_ar', models.CharField(blank=True, max_length=300, null=True)),
                ('description_ckb', models.CharField(blank=True, max_length=300, null=True)),
                ('ordinal', models.SmallIntegerField(blank=True, null=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='core.treatment')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('text_en', models.CharField(max_length=50, null=True)),
                ('text_ar', models.CharField(max_length=50, null=True)),
                ('text_ckb', models.CharField(max_length=50, null=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.treatment')),
            ],
        ),
    ]
