# Generated by Django 5.0.2 on 2024-03-18 19:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_treatment_conditions_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='description_ar',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='description_ckb',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
