# Generated by Django 4.1.13 on 2024-02-19 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.core.modules


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_journey_journeydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('action', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, default='/', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='uploads/user/default-user-avatar.png', null=True, upload_to=src.core.modules.upload_image_file_path)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
