# Generated by Django 4.1.13 on 2024-02-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_treatment_procedure_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='core.service'),
        ),
    ]
