# Generated by Django 5.0.2 on 2024-03-18 19:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_condition_description_alter_procedure_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='description_ar',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='description_ckb',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
