# Generated by Django 4.1.13 on 2024-02-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
