# Generated by Django 4.1.13 on 2024-02-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_procedure_ordinal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['ordinal']},
        ),
    ]
