# Generated by Django 5.0.2 on 2024-03-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_slide_description_ar_slide_description_ckb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='text_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='text_ckb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='text_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='description_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='description_ckb',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='title_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='title_ckb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ckb',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_ckb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ckb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='conditions_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='conditions_description_ckb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='conditions_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='procedure_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='procedure_description_ckb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='procedure_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='title_ckb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
