# Generated by Django 5.0.2 on 2024-03-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_condition_text_ar_condition_text_ckb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ckb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
