# Generated by Django 5.0.2 on 2024-03-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_menu_name_ar_menu_name_ckb_menu_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ordinal',
            field=models.SmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
