# Generated by Django 5.0.2 on 2024-03-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_menu_ordinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ordinal',
            field=models.SmallIntegerField(),
        ),
    ]
