# Generated by Django 5.0.2 on 2024-03-03 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0014_alter_menu_link_alter_menu_ordinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('title_translated', models.JSONField(blank=True, null=True, verbose_name='Translated Title')),
                ('description_translated', models.JSONField(blank=True, null=True, verbose_name='Translated Description')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Section Content',
                'verbose_name_plural': 'Section Contents',
            },
        ),
    ]
