# Generated by Django 5.0.2 on 2024-03-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sectioncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='description_ckb',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='title_ckb',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
