# Generated by Django 5.0.2 on 2024-03-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sectioncontent_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='core.sectioncontent'),
        ),
    ]
