# Generated by Django 5.0.2 on 2024-03-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sectioncontent_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='action_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='action_ckb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='action_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ckb',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ckb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
