# Generated by Django 5.0.2 on 2024-03-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_about_action_ar_about_action_ckb_about_action_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=650),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_ar',
            field=models.CharField(max_length=650, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_ckb',
            field=models.CharField(max_length=650, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_en',
            field=models.CharField(max_length=650, null=True),
        ),
    ]
