# Generated by Django 5.0.2 on 2024-03-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_about_description_alter_about_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='title_ckb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journeydetail',
            name='text_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journeydetail',
            name='text_ckb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journeydetail',
            name='text_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
