# Generated by Django 5.0.2 on 2024-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='text_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_ckb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
