# Generated by Django 4.1.13 on 2024-02-20 18:42

from django.db import migrations, models
import src.core.modules


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='uploads/user/default-user-avatar.png', null=True, upload_to=src.core.modules.upload_image_file_path),
        ),
    ]
