# Generated by Django 5.0.2 on 2024-03-19 11:52

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_ar',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_ckb',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_en',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
