# Generated by Django 5.0.2 on 2024-03-21 13:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description_ar',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description_ckb',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
