# Generated by Django 4.1.13 on 2024-02-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
    ]
