# Generated by Django 4.1.13 on 2024-02-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('ku', 'Kurdish')], default='en', max_length=3, unique=True),
        ),
    ]
